/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemosSalonRouteImport } from './routes/demos.salon'
import { Route as DemosGymRouteImport } from './routes/demos.gym'
import { Route as DemosCafeRouteImport } from './routes/demos.cafe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosSalonRoute = DemosSalonRouteImport.update({
  id: '/demos/salon',
  path: '/demos/salon',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosGymRoute = DemosGymRouteImport.update({
  id: '/demos/gym',
  path: '/demos/gym',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosCafeRoute = DemosCafeRouteImport.update({
  id: '/demos/cafe',
  path: '/demos/cafe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demos/cafe': typeof DemosCafeRoute
  '/demos/gym': typeof DemosGymRoute
  '/demos/salon': typeof DemosSalonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demos/cafe': typeof DemosCafeRoute
  '/demos/gym': typeof DemosGymRoute
  '/demos/salon': typeof DemosSalonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demos/cafe': typeof DemosCafeRoute
  '/demos/gym': typeof DemosGymRoute
  '/demos/salon': typeof DemosSalonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demos/cafe' | '/demos/gym' | '/demos/salon'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demos/cafe' | '/demos/gym' | '/demos/salon'
  id: '__root__' | '/' | '/demos/cafe' | '/demos/gym' | '/demos/salon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemosCafeRoute: typeof DemosCafeRoute
  DemosGymRoute: typeof DemosGymRoute
  DemosSalonRoute: typeof DemosSalonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/salon': {
      id: '/demos/salon'
      path: '/demos/salon'
      fullPath: '/demos/salon'
      preLoaderRoute: typeof DemosSalonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/gym': {
      id: '/demos/gym'
      path: '/demos/gym'
      fullPath: '/demos/gym'
      preLoaderRoute: typeof DemosGymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/cafe': {
      id: '/demos/cafe'
      path: '/demos/cafe'
      fullPath: '/demos/cafe'
      preLoaderRoute: typeof DemosCafeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemosCafeRoute: DemosCafeRoute,
  DemosGymRoute: DemosGymRoute,
  DemosSalonRoute: DemosSalonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
